### ISSUE TITLE
`vagrant pe-build copy` crashes

### ISSUE THREAD

**Issue by adrienthebo** [oscar-stack/vagrant-pe_build#43]
```
vagrant12 pe-build copy --version 3.0.1 --dir https://s3.amazonaws.com/pe-builds/released/:version puppet-enterprise-:version-debian-6-i386.tar.gz
/home/adrien/development/vagrant-dev/vagrant-pe_build/lib/pe_build/command/copy.rb:33:in `block (2 levels) in parser': undefined local variable or method `options' for #<PEBuild::Command::Copy:0x000000038549d8> (NameError)
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1360:in `call'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1360:in `block in parse_in_order'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1347:in `catch'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1347:in `parse_in_order'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1341:in `order!'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1432:in `permute!'
	from /home/adrien/.rbenv/versions/1.9.3-p392/lib/ruby/1.9.1/optparse.rb:1453:in `parse!'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/vagrant/lib/vagrant/plugin/v2/command.rb:51:in `parse_options'
	from /home/adrien/development/vagrant-dev/vagrant-pe_build/lib/pe_build/command/copy.rb:11:in `execute'
	from /home/adrien/development/vagrant-dev/vagrant-pe_build/lib/pe_build/command/base.rb:32:in `execute_subcommand'
	from /home/adrien/development/vagrant-dev/vagrant-pe_build/lib/pe_build/command/base.rb:18:in `execute'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/vagrant/lib/vagrant/cli.rb:46:in `execute'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/vagrant/lib/vagrant/environment.rb:467:in `cli'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/vagrant/bin/vagrant:84:in `<top (required)>'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/bin/vagrant:16:in `load'
	from /home/adrien/local/share/rbenv/gemsets/vagrant12/bin/vagrant:16:in `<main>'

```

**Comment by Sharpie** [comment]
Looks like this was fixed by 53c2fc2 in 0.8.1.
